#############################################################################
# Makefile for building: modeling
# Generated by qmake (2.01a) (Qt 4.6.2) on: Sun Nov 14 17:37:38 2010
# Project:  modeling.pro
# Template: app
# Command: /home/misha/Documents/Distributives/QTSDK/qt/bin/qmake -spec ../../Distributives/QTSDK/qt/mkspecs/linux-g++ -unix -o Makefile modeling.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../Distributives/QTSDK/qt/mkspecs/linux-g++ -I. -I../../Distributives/QTSDK/qt/include/QtCore -I../../Distributives/QTSDK/qt/include/QtGui -I../../Distributives/QTSDK/qt/include/QtOpenGL -I../../Distributives/QTSDK/qt/include -I/usr/X11R6/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/misha/Documents/Distributives/QTSDK/qt/lib
LIBS          = $(SUBLIBS)  -L/home/misha/Documents/Distributives/QTSDK/qt/lib -L/usr/X11R6/lib -lglut -lQtOpenGL -L/home/misha/Documents/Distributives/QTSDK/qt/lib -L/usr/X11R6/lib -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/misha/Documents/Distributives/QTSDK/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainclass.cpp \
		vector.cpp \
		paintingclass.cpp moc_mainclass.cpp \
		moc_ball.cpp \
		moc_paintingclass.cpp
OBJECTS       = main.o \
		mainclass.o \
		vector.o \
		paintingclass.o \
		moc_mainclass.o \
		moc_ball.o \
		moc_paintingclass.o
DIST          = ../../Distributives/QTSDK/qt/mkspecs/common/g++.conf \
		../../Distributives/QTSDK/qt/mkspecs/common/unix.conf \
		../../Distributives/QTSDK/qt/mkspecs/common/linux.conf \
		../../Distributives/QTSDK/qt/mkspecs/qconfig.pri \
		../../Distributives/QTSDK/qt/mkspecs/features/qt_functions.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/qt_config.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/exclusive_builds.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/default_pre.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/release.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/default_post.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/warn_on.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/qt.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/unix/opengl.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/unix/thread.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/moc.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/resources.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/uic.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/yacc.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/lex.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/include_source_dir.prf \
		modeling.pro
QMAKE_TARGET  = modeling
DESTDIR       = 
TARGET        = modeling

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: modeling.pro  ../../Distributives/QTSDK/qt/mkspecs/linux-g++/qmake.conf ../../Distributives/QTSDK/qt/mkspecs/common/g++.conf \
		../../Distributives/QTSDK/qt/mkspecs/common/unix.conf \
		../../Distributives/QTSDK/qt/mkspecs/common/linux.conf \
		../../Distributives/QTSDK/qt/mkspecs/qconfig.pri \
		../../Distributives/QTSDK/qt/mkspecs/features/qt_functions.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/qt_config.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/exclusive_builds.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/default_pre.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/release.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/default_post.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/warn_on.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/qt.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/unix/opengl.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/unix/thread.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/moc.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/resources.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/uic.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/yacc.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/lex.prf \
		../../Distributives/QTSDK/qt/mkspecs/features/include_source_dir.prf \
		/home/misha/Documents/Distributives/QTSDK/qt/lib/libQtOpenGL.prl \
		/home/misha/Documents/Distributives/QTSDK/qt/lib/libQtGui.prl \
		/home/misha/Documents/Distributives/QTSDK/qt/lib/libQtCore.prl
	$(QMAKE) -spec ../../Distributives/QTSDK/qt/mkspecs/linux-g++ -unix -o Makefile modeling.pro
../../Distributives/QTSDK/qt/mkspecs/common/g++.conf:
../../Distributives/QTSDK/qt/mkspecs/common/unix.conf:
../../Distributives/QTSDK/qt/mkspecs/common/linux.conf:
../../Distributives/QTSDK/qt/mkspecs/qconfig.pri:
../../Distributives/QTSDK/qt/mkspecs/features/qt_functions.prf:
../../Distributives/QTSDK/qt/mkspecs/features/qt_config.prf:
../../Distributives/QTSDK/qt/mkspecs/features/exclusive_builds.prf:
../../Distributives/QTSDK/qt/mkspecs/features/default_pre.prf:
../../Distributives/QTSDK/qt/mkspecs/features/release.prf:
../../Distributives/QTSDK/qt/mkspecs/features/default_post.prf:
../../Distributives/QTSDK/qt/mkspecs/features/warn_on.prf:
../../Distributives/QTSDK/qt/mkspecs/features/qt.prf:
../../Distributives/QTSDK/qt/mkspecs/features/unix/opengl.prf:
../../Distributives/QTSDK/qt/mkspecs/features/unix/thread.prf:
../../Distributives/QTSDK/qt/mkspecs/features/moc.prf:
../../Distributives/QTSDK/qt/mkspecs/features/resources.prf:
../../Distributives/QTSDK/qt/mkspecs/features/uic.prf:
../../Distributives/QTSDK/qt/mkspecs/features/yacc.prf:
../../Distributives/QTSDK/qt/mkspecs/features/lex.prf:
../../Distributives/QTSDK/qt/mkspecs/features/include_source_dir.prf:
/home/misha/Documents/Distributives/QTSDK/qt/lib/libQtOpenGL.prl:
/home/misha/Documents/Distributives/QTSDK/qt/lib/libQtGui.prl:
/home/misha/Documents/Distributives/QTSDK/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../Distributives/QTSDK/qt/mkspecs/linux-g++ -unix -o Makefile modeling.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/modeling1.0.0 || $(MKDIR) .tmp/modeling1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/modeling1.0.0/ && $(COPY_FILE) --parents mainclass.h vector.h ball.h paintingclass.h .tmp/modeling1.0.0/ && $(COPY_FILE) --parents main.cpp mainclass.cpp vector.cpp paintingclass.cpp .tmp/modeling1.0.0/ && (cd `dirname .tmp/modeling1.0.0` && $(TAR) modeling1.0.0.tar modeling1.0.0 && $(COMPRESS) modeling1.0.0.tar) && $(MOVE) `dirname .tmp/modeling1.0.0`/modeling1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/modeling1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainclass.cpp moc_ball.cpp moc_paintingclass.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainclass.cpp moc_ball.cpp moc_paintingclass.cpp
moc_mainclass.cpp: vector.h \
		paintingclass.h \
		ball.h \
		mainclass.h
	/home/misha/Documents/Distributives/QTSDK/qt/bin/moc $(DEFINES) $(INCPATH) mainclass.h -o moc_mainclass.cpp

moc_ball.cpp: vector.h \
		ball.h
	/home/misha/Documents/Distributives/QTSDK/qt/bin/moc $(DEFINES) $(INCPATH) ball.h -o moc_ball.cpp

moc_paintingclass.cpp: ball.h \
		vector.h \
		paintingclass.h
	/home/misha/Documents/Distributives/QTSDK/qt/bin/moc $(DEFINES) $(INCPATH) paintingclass.h -o moc_paintingclass.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainclass.h \
		vector.h \
		paintingclass.h \
		ball.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainclass.o: mainclass.cpp mainclass.h \
		vector.h \
		paintingclass.h \
		ball.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainclass.o mainclass.cpp

vector.o: vector.cpp vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vector.o vector.cpp

paintingclass.o: paintingclass.cpp paintingclass.h \
		ball.h \
		vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paintingclass.o paintingclass.cpp

moc_mainclass.o: moc_mainclass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainclass.o moc_mainclass.cpp

moc_ball.o: moc_ball.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ball.o moc_ball.cpp

moc_paintingclass.o: moc_paintingclass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_paintingclass.o moc_paintingclass.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

